// List of all Quran Surahs with their details

class QuranSurah {
  final int number;
  final String arabicName;
  final String englishName;
  final int verses;
  final int juz;
  
  const QuranSurah({
    required this.number,
    required this.arabicName,
    required this.englishName,
    required this.verses,
    required this.juz,
  });
}

class QuranConstants {
  static const List<QuranSurah> surahs = [
    QuranSurah(number: 1, arabicName: 'الفاتحة', englishName: 'Al-Fatiha', verses: 7, juz: 1),
    QuranSurah(number: 2, arabicName: 'البقرة', englishName: 'Al-Baqarah', verses: 286, juz: 1),
    QuranSurah(number: 3, arabicName: 'آل عمران', englishName: 'Aal-Imran', verses: 200, juz: 3),
    QuranSurah(number: 4, arabicName: 'النساء', englishName: 'An-Nisa', verses: 176, juz: 4),
    QuranSurah(number: 5, arabicName: 'المائدة', englishName: 'Al-Ma\'idah', verses: 120, juz: 6),
    QuranSurah(number: 6, arabicName: 'الأنعام', englishName: 'Al-An\'am', verses: 165, juz: 7),
    QuranSurah(number: 7, arabicName: 'الأعراف', englishName: 'Al-A\'raf', verses: 206, juz: 8),
    QuranSurah(number: 8, arabicName: 'الأنفال', englishName: 'Al-Anfal', verses: 75, juz: 9),
    QuranSurah(number: 9, arabicName: 'التوبة', englishName: 'At-Tawbah', verses: 129, juz: 10),
    QuranSurah(number: 10, arabicName: 'يونس', englishName: 'Yunus', verses: 109, juz: 11),
    QuranSurah(number: 11, arabicName: 'هود', englishName: 'Hud', verses: 123, juz: 11),
    QuranSurah(number: 12, arabicName: 'يوسف', englishName: 'Yusuf', verses: 111, juz: 12),
    QuranSurah(number: 13, arabicName: 'الرعد', englishName: 'Ar-Ra\'d', verses: 43, juz: 13),
    QuranSurah(number: 14, arabicName: 'إبراهيم', englishName: 'Ibrahim', verses: 52, juz: 13),
    QuranSurah(number: 15, arabicName: 'الحجر', englishName: 'Al-Hijr', verses: 99, juz: 14),
    QuranSurah(number: 16, arabicName: 'النحل', englishName: 'An-Nahl', verses: 128, juz: 14),
    QuranSurah(number: 17, arabicName: 'الإسراء', englishName: 'Al-Isra', verses: 111, juz: 15),
    QuranSurah(number: 18, arabicName: 'الكهف', englishName: 'Al-Kahf', verses: 110, juz: 15),
    QuranSurah(number: 19, arabicName: 'مريم', englishName: 'Maryam', verses: 98, juz: 16),
    QuranSurah(number: 20, arabicName: 'طه', englishName: 'Ta-Ha', verses: 135, juz: 16),
    QuranSurah(number: 21, arabicName: 'الأنبياء', englishName: 'Al-Anbiya', verses: 112, juz: 17),
    QuranSurah(number: 22, arabicName: 'الحج', englishName: 'Al-Hajj', verses: 78, juz: 17),
    QuranSurah(number: 23, arabicName: 'المؤمنون', englishName: 'Al-Mu\'minun', verses: 118, juz: 18),
    QuranSurah(number: 24, arabicName: 'النور', englishName: 'An-Nur', verses: 64, juz: 18),
    QuranSurah(number: 25, arabicName: 'الفرقان', englishName: 'Al-Furqan', verses: 77, juz: 18),
    QuranSurah(number: 26, arabicName: 'الشعراء', englishName: 'Ash-Shu\'ara', verses: 227, juz: 19),
    QuranSurah(number: 27, arabicName: 'النمل', englishName: 'An-Naml', verses: 93, juz: 19),
    QuranSurah(number: 28, arabicName: 'القصص', englishName: 'Al-Qasas', verses: 88, juz: 20),
    QuranSurah(number: 29, arabicName: 'العنكبوت', englishName: 'Al-Ankabut', verses: 69, juz: 20),
    QuranSurah(number: 30, arabicName: 'الروم', englishName: 'Ar-Rum', verses: 60, juz: 21),
    QuranSurah(number: 31, arabicName: 'لقمان', englishName: 'Luqman', verses: 34, juz: 21),
    QuranSurah(number: 32, arabicName: 'السجدة', englishName: 'As-Sajdah', verses: 30, juz: 21),
    QuranSurah(number: 33, arabicName: 'الأحزاب', englishName: 'Al-Ahzab', verses: 73, juz: 21),
    QuranSurah(number: 34, arabicName: 'سبأ', englishName: 'Saba', verses: 54, juz: 22),
    QuranSurah(number: 35, arabicName: 'فاطر', englishName: 'Fatir', verses: 45, juz: 22),
    QuranSurah(number: 36, arabicName: 'يس', englishName: 'Ya-Sin', verses: 83, juz: 22),
    QuranSurah(number: 37, arabicName: 'الصافات', englishName: 'As-Saffat', verses: 182, juz: 23),
    QuranSurah(number: 38, arabicName: 'ص', englishName: 'Sad', verses: 88, juz: 23),
    QuranSurah(number: 39, arabicName: 'الزمر', englishName: 'Az-Zumar', verses: 75, juz: 23),
    QuranSurah(number: 40, arabicName: 'غافر', englishName: 'Ghafir', verses: 85, juz: 24),
    QuranSurah(number: 41, arabicName: 'فصلت', englishName: 'Fussilat', verses: 54, juz: 24),
    QuranSurah(number: 42, arabicName: 'الشورى', englishName: 'Ash-Shura', verses: 53, juz: 25),
    QuranSurah(number: 43, arabicName: 'الزخرف', englishName: 'Az-Zukhruf', verses: 89, juz: 25),
    QuranSurah(number: 44, arabicName: 'الدخان', englishName: 'Ad-Dukhan', verses: 59, juz: 25),
    QuranSurah(number: 45, arabicName: 'الجاثية', englishName: 'Al-Jathiyah', verses: 37, juz: 25),
    QuranSurah(number: 46, arabicName: 'الأحقاف', englishName: 'Al-Ahqaf', verses: 35, juz: 26),
    QuranSurah(number: 47, arabicName: 'محمد', englishName: 'Muhammad', verses: 38, juz: 26),
    QuranSurah(number: 48, arabicName: 'الفتح', englishName: 'Al-Fath', verses: 29, juz: 26),
    QuranSurah(number: 49, arabicName: 'الحجرات', englishName: 'Al-Hujurat', verses: 18, juz: 26),
    QuranSurah(number: 50, arabicName: 'ق', englishName: 'Qaf', verses: 45, juz: 26),
    QuranSurah(number: 51, arabicName: 'الذاريات', englishName: 'Adh-Dhariyat', verses: 60, juz: 26),
    QuranSurah(number: 52, arabicName: 'الطور', englishName: 'At-Tur', verses: 49, juz: 27),
    QuranSurah(number: 53, arabicName: 'النجم', englishName: 'An-Najm', verses: 62, juz: 27),
    QuranSurah(number: 54, arabicName: 'القمر', englishName: 'Al-Qamar', verses: 55, juz: 27),
    QuranSurah(number: 55, arabicName: 'الرحمن', englishName: 'Ar-Rahman', verses: 78, juz: 27),
    QuranSurah(number: 56, arabicName: 'الواقعة', englishName: 'Al-Waqi\'ah', verses: 96, juz: 27),
    QuranSurah(number: 57, arabicName: 'الحديد', englishName: 'Al-Hadid', verses: 29, juz: 27),
    QuranSurah(number: 58, arabicName: 'المجادلة', englishName: 'Al-Mujadilah', verses: 22, juz: 28),
    QuranSurah(number: 59, arabicName: 'الحشر', englishName: 'Al-Hashr', verses: 24, juz: 28),
    QuranSurah(number: 60, arabicName: 'الممتحنة', englishName: 'Al-Mumtahanah', verses: 13, juz: 28),
    QuranSurah(number: 61, arabicName: 'الصف', englishName: 'As-Saff', verses: 14, juz: 28),
    QuranSurah(number: 62, arabicName: 'الجمعة', englishName: 'Al-Jumu\'ah', verses: 11, juz: 28),
    QuranSurah(number: 63, arabicName: 'المنافقون', englishName: 'Al-Munafiqun', verses: 11, juz: 28),
    QuranSurah(number: 64, arabicName: 'التغابن', englishName: 'At-Taghabun', verses: 18, juz: 28),
    QuranSurah(number: 65, arabicName: 'الطلاق', englishName: 'At-Talaq', verses: 12, juz: 28),
    QuranSurah(number: 66, arabicName: 'التحريم', englishName: 'At-Tahrim', verses: 12, juz: 28),
    QuranSurah(number: 67, arabicName: 'الملك', englishName: 'Al-Mulk', verses: 30, juz: 29),
    QuranSurah(number: 68, arabicName: 'القلم', englishName: 'Al-Qalam', verses: 52, juz: 29),
    QuranSurah(number: 69, arabicName: 'الحاقة', englishName: 'Al-Haqqah', verses: 52, juz: 29),
    QuranSurah(number: 70, arabicName: 'المعارج', englishName: 'Al-Ma\'arij', verses: 44, juz: 29),
    QuranSurah(number: 71, arabicName: 'نوح', englishName: 'Nuh', verses: 28, juz: 29),
    QuranSurah(number: 72, arabicName: 'الجن', englishName: 'Al-Jinn', verses: 28, juz: 29),
    QuranSurah(number: 73, arabicName: 'المزمل', englishName: 'Al-Muzzammil', verses: 20, juz: 29),
    QuranSurah(number: 74, arabicName: 'المدثر', englishName: 'Al-Muddaththir', verses: 56, juz: 29),
    QuranSurah(number: 75, arabicName: 'القيامة', englishName: 'Al-Qiyamah', verses: 40, juz: 29),
    QuranSurah(number: 76, arabicName: 'الإنسان', englishName: 'Al-Insan', verses: 31, juz: 29),
    QuranSurah(number: 77, arabicName: 'المرسلات', englishName: 'Al-Mursalat', verses: 50, juz: 29),
    QuranSurah(number: 78, arabicName: 'النبأ', englishName: 'An-Naba', verses: 40, juz: 30),
    QuranSurah(number: 79, arabicName: 'النازعات', englishName: 'An-Nazi\'at', verses: 46, juz: 30),
    QuranSurah(number: 80, arabicName: 'عبس', englishName: 'Abasa', verses: 42, juz: 30),
    QuranSurah(number: 81, arabicName: 'التكوير', englishName: 'At-Takwir', verses: 29, juz: 30),
    QuranSurah(number: 82, arabicName: 'الانفطار', englishName: 'Al-Infitar', verses: 19, juz: 30),
    QuranSurah(number: 83, arabicName: 'المطففين', englishName: 'Al-Mutaffifin', verses: 36, juz: 30),
    QuranSurah(number: 84, arabicName: 'الانشقاق', englishName: 'Al-Inshiqaq', verses: 25, juz: 30),
    QuranSurah(number: 85, arabicName: 'البروج', englishName: 'Al-Buruj', verses: 22, juz: 30),
    QuranSurah(number: 86, arabicName: 'الطارق', englishName: 'At-Tariq', verses: 17, juz: 30),
    QuranSurah(number: 87, arabicName: 'الأعلى', englishName: 'Al-A\'la', verses: 19, juz: 30),
    QuranSurah(number: 88, arabicName: 'الغاشية', englishName: 'Al-Ghashiyah', verses: 26, juz: 30),
    QuranSurah(number: 89, arabicName: 'الفجر', englishName: 'Al-Fajr', verses: 30, juz: 30),
    QuranSurah(number: 90, arabicName: 'البلد', englishName: 'Al-Balad', verses: 20, juz: 30),
    QuranSurah(number: 91, arabicName: 'الشمس', englishName: 'Ash-Shams', verses: 15, juz: 30),
    QuranSurah(number: 92, arabicName: 'الليل', englishName: 'Al-Layl', verses: 21, juz: 30),
    QuranSurah(number: 93, arabicName: 'الضحى', englishName: 'Ad-Duha', verses: 11, juz: 30),
    QuranSurah(number: 94, arabicName: 'الشرح', englishName: 'Ash-Sharh', verses: 8, juz: 30),
    QuranSurah(number: 95, arabicName: 'التين', englishName: 'At-Tin', verses: 8, juz: 30),
    QuranSurah(number: 96, arabicName: 'العلق', englishName: 'Al-Alaq', verses: 19, juz: 30),
    QuranSurah(number: 97, arabicName: 'القدر', englishName: 'Al-Qadr', verses: 5, juz: 30),
    QuranSurah(number: 98, arabicName: 'البينة', englishName: 'Al-Bayyinah', verses: 8, juz: 30),
    QuranSurah(number: 99, arabicName: 'الزلزلة', englishName: 'Az-Zalzalah', verses: 8, juz: 30),
    QuranSurah(number: 100, arabicName: 'العاديات', englishName: 'Al-Adiyat', verses: 11, juz: 30),
    QuranSurah(number: 101, arabicName: 'القارعة', englishName: 'Al-Qari\'ah', verses: 11, juz: 30),
    QuranSurah(number: 102, arabicName: 'التكاثر', englishName: 'At-Takathur', verses: 8, juz: 30),
    QuranSurah(number: 103, arabicName: 'العصر', englishName: 'Al-Asr', verses: 3, juz: 30),
    QuranSurah(number: 104, arabicName: 'الهمزة', englishName: 'Al-Humazah', verses: 9, juz: 30),
    QuranSurah(number: 105, arabicName: 'الفيل', englishName: 'Al-Fil', verses: 5, juz: 30),
    QuranSurah(number: 106, arabicName: 'قريش', englishName: 'Quraysh', verses: 4, juz: 30),
    QuranSurah(number: 107, arabicName: 'الماعون', englishName: 'Al-Ma\'un', verses: 7, juz: 30),
    QuranSurah(number: 108, arabicName: 'الكوثر', englishName: 'Al-Kawthar', verses: 3, juz: 30),
    QuranSurah(number: 109, arabicName: 'الكافرون', englishName: 'Al-Kafirun', verses: 6, juz: 30),
    QuranSurah(number: 110, arabicName: 'النصر', englishName: 'An-Nasr', verses: 3, juz: 30),
    QuranSurah(number: 111, arabicName: 'المسد', englishName: 'Al-Masad', verses: 5, juz: 30),
    QuranSurah(number: 112, arabicName: 'الإخلاص', englishName: 'Al-Ikhlas', verses: 4, juz: 30),
    QuranSurah(number: 113, arabicName: 'الفلق', englishName: 'Al-Falaq', verses: 5, juz: 30),
    QuranSurah(number: 114, arabicName: 'الناس', englishName: 'An-Nas', verses: 6, juz: 30),
  ];
  
  static QuranSurah getSurahByNumber(int number) {
    return surahs.firstWhere((s) => s.number == number);
  }
  
  static List<String> get surahNames => surahs.map((s) => s.arabicName).toList();
  
  static int getVersesCount(int surahNumber) {
    return surahs.firstWhere((s) => s.number == surahNumber).verses;
  }
}
