name: Build Flutter APK

on:
  push:
    branches: [ Zarax34-patch-1 ]  # غيّر حسب حاجتك
  pull_request:
    branches: [ Zarax34-patch-1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.0' # أو الإصدار الذي يناسب مشروعك

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK (debug)
      run: flutter build apk --debug

    - name: Upload Debug APK
      uses: actions/upload-artifact@v3
      with:
        name: app-debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk

    # Optional: build release signed APK
    - name: Decode Keystore
      if: secrets.KEYSTORE_BASE64 != ''
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

    - name: Build APK Release
      if: secrets.KEYSTORE_BASE64 != ''
      run: |
        flutter build apk \
          --release \
          --no-tree-shake-icons \
          --flavor prod \
          --dart-define=FLAVOR=prod \
          -t lib/main.dart
      env:
        JAVA_TOOL_OPTIONS: "-Dfile.encoding=UTF8"

    - name: Upload Release APK
      if: secrets.KEYSTORE_BASE64 != ''
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
